Files already downloaded and verified
Files already downloaded and verified
    step 0:
Training:   0%|                                                                                                                       | 0/10000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "models/WGAN.py", line 158, in <module>
    manager.train()
  File "models/WGAN.py", line 106, in train
    critic_real_mean=self.netD(real).mean()
  File "/home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/__init__.py", line 1172, in __call__
    return self.execute(*args, **kw)
  File "models/WGAN.py", line 58, in execute
    x=self.encoder(x)
  File "/home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/__init__.py", line 1172, in __call__
    return self.execute(*args, **kw)
  File "/home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/nn.py", line 2202, in execute
    x = layer(x)
  File "/home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/__init__.py", line 1172, in __call__
    return self.execute(*args, **kw)
  File "/home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/nn.py", line 959, in execute
    assert C==self.in_channels
AssertionError
Traceback (most recent call last):
  File "models/WGAN.py", line 158, in <module>
    manager.train()
  File "models/WGAN.py", line 106, in train
    critic_real_mean=self.netD(real).mean()
  File "/home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/__init__.py", line 1172, in __call__
    return self.execute(*args, **kw)
  File "models/WGAN.py", line 58, in execute
    x=self.encoder(x)
  File "/home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/__init__.py", line 1172, in __call__
    return self.execute(*args, **kw)
  File "/home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/nn.py", line 2202, in execute
    x = layer(x)
  File "/home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/__init__.py", line 1172, in __call__
    return self.execute(*args, **kw)
  File "/home/zhouqianrui/anaconda3/envs/mc/lib/python3.7/site-packages/jittor/nn.py", line 959, in execute
    assert C==self.in_channels
AssertionError